export const GET_USER_CART_ITEM = "GET_USER_CART_ITEM";
export const REMOVE_USER_CART_ITEM = "REMOVE_USER_CART_ITEM";
export const  UPDATE_CART = "UPDATE_CART";
export const CLEAR_CART = "CLEAR_CART";