export const SET_PRODUCTS = "SET_PRODUCTS";
export const RESET_PRODUCTS = "RESET_PRODUCTS";
export const SET_SPECIFIC_PRODUCT = "SET_SPECIFIC_PRODUCT";
export const RESET_SPECIFIC_PRODUCT = "RESET_SPECIFIC_PRODUCT";

export const SET_CATEGORIES_WITH_SUB_CATEGORIES =
  "SET_CATEGORIES_WITH_SUB_CATEGORIES";
export const RESET_CATEGORIES_WITH_SUB_CATEGORIES =
  "RESET_CATEGORIES_WITH_SUB_CATEGORIES";
export const SET_WORK_IMAGES = "SET_WORK_IMAGES";
export const RESET_WORK_IMAGES = "RESET_WORK_IMAGES";
export const SET_ALL_DEALS = "SET_ALL_DEALS";
export const RESET_ALL_DEALS = "RESET_ALL_DEALS";
export const SET_SPECIFIC_DEALS = "SET_SPECIFIC_DEALS";
export const RESET_SPECIFIC_DEALS = "RESET_SPECIFIC_DEALS";
export const  SET_SERVICE_PRICES = "SET_SERVICE_PRICES";
export const RESET_SERVICE_PRICES = "RESET_SERVICE_PRICES";
