export const SET_SERVICES = "SET_SERVICES";
export const RESET_SERVICES = "RESET_SERVICES";
export const SET_SPECIFIC_SERVICE = "SET_SPECIFIC_SERVICE";
export const RESET_SPECIFIC_SERVICE = "RESET_SPECIFIC_SERVICE";

